
import mongoose ,{Schema} from "mongoose"
import jwt from "jsonwebtoken"
import bcrypt from "bcrypt"

const userSchema=new Schema({
    // id:{
    //     type:String,
    //     required:true
    // },
    username:{
        type:String,
        unique:true,
        required:true,
        lowercase:true,
        trim:true,
        index:true
    },
     email:{
        type:String,
        unique:true,
        required:true,
        lowercase:true,
        trim:true,
        
    },
     fullname:{
        type:String,
        required:true,
        trim:true,
        index:true
        
    },
    avatar:{
        type:String,
        //cloudinary url
        // required:true,
        
    },
    coverImage:{
        type:String,//cloudinary url
        
    },
   watchHistory: [
            {
                type: Schema.Types.ObjectId,
                ref: "Video"
            }
        ],
    password:{
        type:String,
        required:[true,"Password is required"]//you can send addional msg with required
    
    },
    refreshToken:{
        type:String,

    }

},{timestamps:true})
/*
A pre hook is middleware that executes before a database operation, 
commonly used in Mongoose to modify or validate data before saving.

*/

//while using pre we cant use arrow function for callback as we we know 
//arow function doesnt have access to this and here we have to use this
//so we can refer schema in this context
//it is async as it require time
userSchema.pre("save",async function(next){
  
    /*it will run everytime when we save but we have to perform action on 
    password only if it modified*/
    
    //if password is not modified go next
    if(!this.isModified("password")) return next()
    //if it is modified
    this.password=await bcrypt.hash(this.password,10)
    next();
         
})

//custom function
userSchema.methods.isPasswordCorrect=async function(password){
   return await bcrypt.compare(password,this.password)
   //bcrypt.compare(user-entered password,stored hashed password from DB)
}

/*A JWT consists of three parts, separated by dots (.)
Header. Payload. Signature
header is autogenerated
signature is generated using the header, payload, and a secret key*/

userSchema.methods.generateAccessToken=function(){
    //jwt.sign(payload, secretKey, options)
   return   jwt.sign({
        _id:this._id,
        email:this.email,
        username:this.username,
        fullname:this.fullname

    },
    process.env.ACCESS_TOKEN_SECRET,
    {
        expiresIn:process.env.ACCESS_TOKEN_EXPIRY
    }

)

}
userSchema.methods.generateRefreshToken=function(){
    return   jwt.sign({
        _id:this._id,
      
    },
    process.env.REFRESH_TOKEN_SECRET,
    {
        expiresIn:process.env.REFRESH_TOKEN_EXPIRY
    }

)
}
export const User=mongoose.model("User",userSchema)


//topics:

/*--------------bcrypt---------------*/

//bcrypt = a password hashing library.
// It is used to secure passwords before saving them to the database.

// How bcrypt works (simple)
// 1) User enters password
// 2) bcrypt adds "salt" (random string)
// Salt = a random string added to your password before hashing.
// 3) bcrypt hashes the password + salt
// 4) Only the hash is saved in DB
// 5) During login → bcrypt compares hash with raw password